##
##  
##  # Default Kibana configuration for docker target
server.name: kibana
server.host: "0.0.0.0"
#这里写你的es第一个node的地址
elasticsearch.url: "http://es01:9200"
xpack.monitoring.ui.container.elasticsearch.enabled: true
#i18n.locale: "zh-CN"
